# Generated by Django 4.2.4 on 2023-09-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="name",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="url",
            field=models.ImageField(default="test.jpg", upload_to=None),
        ),
    ]
