# Generated by Django 4.2.4 on 2023-10-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productline",
            name="attribute_value",
            field=models.ManyToManyField(
                related_name="product_line_attribute_value",
                through="product.ProductLineAttributeValue",
                to="product.attributevalue",
            ),
        ),
    ]
